In [1]:
import pickle

In [2]:
path = '/workspace/experiment/log/noisyFeature/2'

In [4]:
import os 
import torch

In [6]:
model = torch.load(path+"/t.ckpt")

In [7]:
model.keys()

dict_keys(['epoch', 'global_step', 'pytorch-lightning_version', 'state_dict', 'hparams_name', 'hyper_parameters'])

In [8]:
model['hparams_name']

'kwargs'

In [119]:
import torch.nn as nn

conv2 = nn.Conv2d(128, 128, 3, 1, 1)

In [138]:
tin = torch.randn(1, 128, 8, 8)

In [139]:
conv2(tin).shape

torch.Size([1, 128, 8, 8])

In [5]:
jj

tensor([[False, False, False, False, False, False, False,  True, False, False,
         False, False],
        [False, False, False, False, False, False, False, False,  True,  True,
          True,  True],
        [False, False,  True, False, False,  True, False, False, False, False,
         False, False],
        [False,  True, False,  True,  True, False, False, False, False, False,
         False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False],
        [ True, False, False, False, False, False,  True, False, False, False,
         False, False]])

In [6]:
a = dict()

In [7]:
a['0'] = 0

In [8]:
a

{'0': 0}

In [9]:
a = torch.randn(128, 8, 8)
b = torch.randn(128, 8, 8)

In [10]:
torch.cat([a, b], dim=1).shape

torch.Size([128, 16, 8])

In [11]:
import numpy as np

In [13]:
a = torch.zeros(32, 128, 8, 8)
b = torch.ones(32, 128, 8, 8)
channel_select = torch.randint(0, 128, (int(128 * 0.5), ))
newY = torch.randperm(32)

In [23]:
a[:, channel_select, :, :] = b[newY][:, channel_select, :, :]

In [2]:
import torch
Y_MAT = torch.Tensor(
    [ [0, 6, 7, 8, 9, 10],
      [6, 1, 12, 13, 14, 15],
      [7, 12, 2, 16, 17, 18],
      [8, 13, 16, 3, 19, 20],
      [9, 14, 17, 19, 4, 21],
      [10, 15, 18, 20, 21, 5]
    ]
)

In [3]:
Y_MAT

tensor([[ 0.,  7.,  8.,  9., 10., 11.],
        [ 7.,  1., 12., 13., 14., 15.],
        [ 8., 12.,  2., 16., 17., 18.],
        [ 9., 13., 16.,  3., 19., 20.],
        [10., 14., 17., 19.,  4., 21.],
        [11., 15., 18., 20., 21.,  5.]])

In [38]:
a = [ list(range(6)) for _ in range(6)]
start = 6
for i in range(6):
    for j in range(i, 6):
        if i == j:
            a[i][j] = i
        else:
            a[i][j] = start
            a[j][i] = start
            start += 1

In [41]:
ta = torch.Tensor(a)

In [43]:
ta[y, y2].shape

tensor([11., 14.,  1., 20.,  0., 11., 18.,  8.,  6., 11.,  3., 20.])

In [26]:
index

tensor([[1],
        [2]])

In [27]:
a[index]

tensor([[[ 6.,  1., 11., 12., 13., 14.]],

        [[ 7., 11.,  2., 15., 16., 17.]]])

In [28]:
a[1, 2]

tensor(11.)

In [29]:
y = torch.randint(0, 6, (12, ))
y2 = torch.randint(0, 6, (12, ))

In [30]:
a[y, y2]

tensor([11., 14.,  1., 20.,  0., 11., 18.,  8.,  6., 11.,  3., 20.])

In [31]:
y

tensor([1, 1, 1, 5, 0, 1, 4, 3, 1, 1, 3, 5])

In [32]:
y2

tensor([2, 5, 1, 4, 0, 2, 3, 0, 0, 2, 3, 4])

In [37]:
a[5, 4]

tensor(20.)

In [44]:
import random

In [80]:
random.randint(0, 3)

1

In [83]:
5 % 4

1

In [84]:
4 % 4

0

In [85]:
for i in range(10):
    print(i % 4)

0
1
2
3
0
1
2
3
0
1


In [94]:
a= torch.randn(10)

In [95]:
a[0]

tensor(0.8426)

In [96]:
b = a.clone()

In [97]:
b[0] = 999

In [98]:
a

tensor([ 0.8426, -0.9498, -0.2587,  0.8316, -0.3961,  0.0968, -1.3733, -0.8227,
         0.2687,  0.2610])

In [99]:
a  + b

tensor([ 9.9984e+02, -1.8997e+00, -5.1736e-01,  1.6632e+00, -7.9223e-01,
         1.9366e-01, -2.7467e+00, -1.6455e+00,  5.3741e-01,  5.2200e-01])

In [100]:
b

tensor([ 9.9900e+02, -9.4984e-01, -2.5868e-01,  8.3160e-01, -3.9611e-01,
         9.6832e-02, -1.3733e+00, -8.2274e-01,  2.6870e-01,  2.6100e-01])

In [101]:
weight_path = '/workspace/experiment/result/checkpoints/s0.ckpt'

In [102]:
std = torch.load(weight_path)

In [103]:
std.keys()

dict_keys(['epoch', 'global_step', 'pytorch-lightning_version', 'state_dict', 'hparams_name', 'hyper_parameters'])

In [169]:
def weights_init(m):
    classname = m.__class__.__name__
    if classname.find('Conv') != -1:
        m.weight.data.normal_(0.0, 0.05)
    elif classname.find('BatchNorm') != -1:
        m.weight.data.normal_(1.0, 0.02)
        m.bias.data.fill_(0)
        
class NoiseEncoder(nn.Module):
    def __init__(self, 
                 channel_in:  int,
                 channel_out: int,
                 kernel_size: int,
                 stride:      int,
                 padding:     int,
                 bias:        bool=False, 
                 num_classes: int=6,
                 alpha: float=1.0):
        
        super(self.__class__, self).__init__()
        self.conv = nn.Conv2d(channel_in, channel_out, kernel_size, stride, padding, bias=bias)
        self.bn = nn.BatchNorm2d(channel_out)
        self.bn_noise = nn.BatchNorm2d(channel_out)
        self.activation = nn.LeakyReLU(0.2)
        self.num_classes = num_classes
        self.register_buffer('buffer', None)
        self.alpha = alpha
        
    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        x = self.activation(x)
        return x
    
    def forward_clean(self, x, class_mask):
        x = self.conv(x)
        self.cal_class_per_std(x, class_mask)
        x = self.bn(x)
        x = self.activation(x)
        return x
        
    def forward_noise(self, x, newY):
        x = self.conv(x)
        x = x + self.alpha * torch.normal(mean=0, std=self.buffer[newY]).type_as(x)
        x = self.bn_noise(x)
        x = self.activation(x)
        return x
    
    def cal_class_per_std(self, x, idxs):
        std = []
        for i in range(self.num_classes):
            x_ = x[idxs[i]].detach().clone()
            
            std.append(x_.std(0))
        self.buffer = torch.stack(std)

class classifier32(nn.Module):
    def __init__(self, num_classes=2, alpha=1.0, **kwargs):
        super(self.__class__, self).__init__()
        self.num_classes = num_classes
        self.alpha = alpha
        self.conv1 = NoiseEncoder(3,     64,    3, 1, 1, bias=False, num_classes=num_classes)
        self.conv2 = NoiseEncoder(64,    64,    3, 1, 1, bias=False, num_classes=num_classes)
        self.conv3 = NoiseEncoder(64,   128,    3, 2, 1, bias=False, num_classes=num_classes)
        
        self.conv4 = NoiseEncoder(128,  128,    3, 1, 1, bias=False, num_classes=num_classes)
        self.conv5 = NoiseEncoder(128,  128,    3, 1, 1, bias=False, num_classes=num_classes)
        self.conv6 = NoiseEncoder(128,  128,    3, 2, 1, bias=False, num_classes=num_classes)
        
        self.conv7 = NoiseEncoder(128,  128,    3, 1, 1, bias=False, num_classes=num_classes)
        self.conv8 = NoiseEncoder(128,  128,    3, 1, 1, bias=False, num_classes=num_classes)
        self.conv9 = NoiseEncoder(128,  128,    3, 2, 1, bias=False, num_classes=num_classes)
        
        self.fc = nn.Linear(128, num_classes * (num_classes - 1))
        self.dr1 = nn.Dropout2d(0.2)
        self.dr2 = nn.Dropout2d(0.2)
        self.dr3 = nn.Dropout2d(0.2)
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        self.buffer = None
        self.position = 0
        self.apply(weights_init)
        
    def block0(self, x):
        x = self.dr1(x)
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        return x
    
    def block1(self, x):
        x = self.dr2(x)
        x = self.conv4(x)
        x = self.conv5(x)
        x = self.conv6(x)

        return x
    
    def block2(self, x):
        x = self.dr3(x)
        x = self.conv7(x)
        x = self.conv8(x)
        x = self.conv9(x)
        
        x = self.avgpool(x)
        x = x.view(x.shape[0], -1)
        
        return x
        
    def forward(self, x):
        l1 = self.block0(x)
        l2 = self.block1(l1)
        l3 = self.block2(l2)
        
        y = self.fc(l3)
        
        return {
            'logit': y,
            'l3': l3,
            'l2': l2,
            'l1': l1,
        }
        
    def cal_mean_std(self, x, eps=1e-5):
        size = x.size()
        assert (len(size) == 4)
        B, C = size[:2]
        variance = x.view(B, C, -1).var(dim=2) + eps
        std = variance.sqrt().view(B, C, 1, 1)
        mean = x.view(B, C, -1).mean(dim=2).view(B, C, 1, 1)
        
        return mean, std
    
    def mix_(self, x1, x2):
        size = x1.size()
        x1_mean, x1_std = self.cal_mean_std(x1)
        x2_mean, x2_std = self.cal_mean_std(x2)
        
        x1_normalize = (x1 - x1_mean.expand(size)) / x1_std.expand(size)
        
        return x1_normalize * x1_std.expand(size) + x2_mean.expand(size)
    
    def normalize(self, x, mean, std):
        size = x.size()
        return (x - mean.expand(size)) / std.expand(size)
    
    def unnormalize(self, x, mean, std):
        size = x.size()
        return x * std.expand(size) + mean.expand(size)
    
    def cal_std(self, x, y, mean, std):
        stds = []
        normalize = (x - mean.expand(x.size())) / std.expand(x.size())
        idxs = y.unsqueeze(0) == torch.arange(self.num_classes).unsqueeze(1).type_as(y)
        for i in range(self.num_classes):
            x_ = normalize[idxs[i]].detach().clone()
            
            stds.append(x_.std(0))
            
        self.buffer = torch.stack(stds)

    def forward_norm_std(self, x, y):
        newY = self.cal_index(y)
        x = self.block0(x)
        x = self.block1(x)
        
        mean, std = self.cal_mean_std(x)
        self.cal_std(x, y, mean, std)
        x_norm = self.normalize(x, mean, std)
        x_new = x_norm + self.alpha * torch.normal(mean=0, std=torch.ones_like(x_norm)).type_as(x)
        x_new = self.unnormalize(x_new, mean, std)
        
        clean_x = self.block2(x)
        clean_logit = self.fc(clean_x)
        
        noise_x = self.block2(x_new)
        noise_logit = self.fc(noise_x)
        
        return {
            'clean_x': x,
            'clean_logit': clean_logit,
            'noise_x': x_new,
            'noise_logit': noise_logit,
            'mean': mean,
            'std': std
        }
        
    def forward_l2(self, x):
        l3 = self.block2(x)
        
        logit = self.fc(l3)
        return {
            'logit': logit,
            'l3': l3
        }
    
    def forward_mix(self, x, y):
        newY = self.cal_index(y)

        l1 = self.block0(x)
        l2 = self.block1(l1)
        
        m_l2 = self.mix_(l2, l2[newY])
        l3 = self.block2(l2)
        m_l3 = self.block2(m_l2)
        
        logit = self.fc(l3)
        m_logit = self.fc(m_l3)
        
        return {
            'logit': logit,
            'l2': l2,
            'm_l2': m_l2,
            'm_logit': m_logit,
            'newY': newY
        }
    
    def cal_index(self, y):
        batch_size = y.size(0)
        new_index = torch.randperm(batch_size).type_as(y)
        newY = y[new_index]
        mask = (newY == y)
        while mask.any().item():
            newY[mask] = torch.randint(0, self.num_classes, (torch.sum(mask),)).type_as(y)
            mask = (newY == y)
        return newY
    
    def channel_swap(self, x, y):
        # newY = self.cal_index(y)
        B, C, H, W = x.size()
        channel_select = torch.randint(0, C, (int(C * self.alpha),)).type_as(y)
        # x[:, channel_select, :, :] = x[y][:,channel_select, :, :].clone().detach()
        x[:, channel_select, :, :] = x[y][:,channel_select, :, :]
        return x
    
    def get_position(self):
        self.position = (self.position + 1) % 4
        return self.position
    
    def channel_cutmix(self, x, y):
        B, C, H, W = y.size()
        win_size = int(H / 2)
        pos = self.get_position()
        
    def forward_swap(self, x, y):
        l1 = self.block0(x)
        
        l2 = self.block1(l1)
        # m_l2 = self.block1(m_l1)
        
        # newY = self.cal_index(y)
        newY = torch.randperm(x.size(0))
        m_l2 = self.channel_swap(l2.clone(), newY)
        
        l3 = self.block2(l2)
        m_l3 = self.block2(m_l2)
        
        logit = self.fc(l3)
        m_logit = self.fc(m_l3)
        
        return {
            'clean_logit': logit,
            # 'l2': l2,
            'noise_logit': m_logit,
            'm_l3': m_l3,
            'newY': y[newY]
        }

class Generator(nn.Module):
    def __init__(self, in_channel, out_channel):
        super(self.__class__, self).__init__()
        self.main = nn.Sequential(
            nn.Conv2d(in_channel, out_channel, 3, 1, 1, bias=False),
            nn.BatchNorm2d(out_channel),
            nn.LeakyReLU(0.2),
            
            nn.Conv2d(out_channel, out_channel, 3, 1, 1, bias=False),
            nn.BatchNorm2d(out_channel),
            nn.LeakyReLU(0.2),
            
            nn.Conv2d(in_channel, out_channel, 3, 1, 1, bias=False),
            nn.BatchNorm2d(out_channel),
            nn.LeakyReLU(0.2),
            )
        
    def forward(self, x):
        output = self.main(x)
        return output
    
class Discriminator(nn.Module):
    def __init__(self, in_channel, out_channel):
        super(self.__class__, self).__init__()
        self.main = nn.Sequential(
            nn.Conv2d(in_channel, out_channel, 3, 1, 1, bias=False),
            nn.BatchNorm2d(out_channel),
            nn.LeakyReLU(0.2),
            
            nn.Conv2d(in_channel, out_channel, 3, 1, 1, bias=False),
            nn.BatchNorm2d(out_channel),
            nn.LeakyReLU(0.2),
            
            nn.Conv2d(in_channel, out_channel, 3, 2, 1, bias=False),
            nn.BatchNorm2d(out_channel),
            nn.LeakyReLU(0.2),
        )
        self.avgpool = nn.AdaptiveAvgPool2d((1,1))
        self.classifier = nn.Sequential(
            nn.Linear(out_channel, 1),
            nn.Sigmoid()
        )
        
    def forward(self, x):
        output = self.main(x)
        output = self.avgpool(output)
        output = output.view(output.size(0), -1)
        output = self.classifier(output).flatten()
        return output

In [170]:
model = classifier32()

In [171]:
G = Generator(128, 128)
D = Discriminator(128, 128)

In [172]:
t_input = torch.randn(5, 3, 32, 32)

In [173]:
a = model(t_input)

In [174]:
a['l2'].shape

torch.Size([5, 128, 8, 8])

In [175]:
d_main = D.main(a['l2'])

In [176]:
d_avg = D.avgpool(d_main)

In [177]:
d_avg.shape

torch.Size([5, 128, 1, 1])

In [178]:
d_out = D(a['l2'])

In [192]:
l1 = model.block0(t_input)
l2 = model.block1(l1)

In [193]:
d_out = D(l2)

In [194]:
d_out

tensor([0.5086, 0.4544, 0.5423, 0.5288, 0.5932], grad_fn=<ViewBackward>)

In [190]:
bce = nn.BCELoss()

In [191]:
bce(d_out, torch.ones_like(d_out))

tensor(0.6444, grad_fn=<BinaryCrossEntropyBackward>)

In [196]:
d_out

tensor([0.5086, 0.4544, 0.5423, 0.5288, 0.5932], grad_fn=<ViewBackward>)